name: Trigger GitHub Pages Update
run-name: Trigger GitHub Pages Update

on:
  push:
    paths:
      - "*.md"
      - "*.py"
      - "!gh-actions-generate-toc.py"
      - ".github/workflows/update-gh-page.yml"
  workflow_dispatch:
  workflow_call:
    secrets:
      PAGES_TOKEN:
        required: true

concurrency:
  group: "gh-pages-update"
  cancel-in-progress: true

jobs:
  trigger-gh-pages-update:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub Actions API
        run: |
          curl -L -f \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAGES_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/CarlGao4/ms-sounds-pages/dispatches \
            -d '{"event_type":"update-pages"}'
